### ISSUE TITLE
[iPhone Dataset] Coordinate system, conventions, pose accuracy

### ISSUE THREAD

**Issue by VC86** [KAIR-BAIR/dycheck#11]
Hello,

I have been playing a bit with your invaluably useful iPhone dataset and I see that, when you import from Record3D, there are some particular choices in the pose storage format that I wanted to double check with you (as I tried to reimport the poses with another geometry library, issues arise by which I cannot reproject the static parts of point clouds correctly).

I see that there is a [transpose of the orientation/rotation matrix](https://github.com/KAIR-BAIR/dycheck/blob/main/dycheck/datasets/iphone.py#L218) among other steps that don't immediately make it clear what coordinate system you are using for the camera, or for the world coordinates, or in which of the two systems your poses are saved.

I would therefore have a few questions:

1. Could you elaborate precisely on the conventions used in your code vs. world coordinate system, camera coordinate system, e.g., XYZ = East-Down-North (as OpenCV/COLMAP)?

2. Assuming this is not a matter of coordinates, how accurate are the poses that were recorded, is there any validation in that sense?

Many thanks 🙇‍♂️

**Comment by NagabhushanSN95** [comment]
@VC86 did you figure this out? If so, what is it? I'm also not able to reproject the points accurately.

**Comment by guanjunwu** [comment]
same problem.

**Comment by guanjunwu** [comment]
well, it seems like its opencv camera config.

**Comment by NagabhushanSN95** [comment]
I thought so too. But even that's not working correctly. Please see [this issue](https://github.com/KAIR-BAIR/dycheck/issues/12)
