### ISSUE TITLE
Ordering of iPhone results in Nerfies/HyperNeRF/NSFF

### ISSUE THREAD

**Issue by dsvilarkovic** [KAIR-BAIR/dycheck#4]
Hey, nice work!

I have run iPhone pretrained models myself (rand_bkgd_depth_dist) for T-NeRF (tnerf), Nerfies (dense), HyperNeRF (ambient) myself and I found that the results found in your tables in a paper have been permuted. The results  I get for "dense" model are the results found in the NSFF table, the results for "ambient" model are the results found in the Nerfies row, and since tnerf has the same results as the original T-NeRF results and I don't have NSFF pretrained model, I assume that NSFF results are in the HyperNeRF row?

**Comment by hangg7** [comment]
Hi Dusan, thanks for raising this issue. Could you be more specific which table you are talking about? Will have a check.

**Comment by STLAND-admin** [comment]
After seeing this issue,  I have run the teddy data of the iPhone dataset. The results is same as given in the BENCHMARK.md. I may verify more later, but if the order is totally right after your check, please let me know.

**Comment by dsvilarkovic** [comment]
Okay, I see that results on BENCHMARK.md are the same ones I got. I was comparing with the [paper](https://arxiv.org/pdf/2210.13445.pdf) results (table 8). I see paper-windmill on BENCHMARK.md and the one found in the paper are differently ordered.

**Comment by hangg7** [comment]
@STLAND-admin @dsvilarkovic Thanks again! I can confirm that the Table 8 has permuted HyperNeRF, NSFF, Nerfies per-scene breakdown results. I will update these tables on arXiv. At the meanwhile, please refer to the [BENCHMARK.md](https://github.com/KAIR-BAIR/dycheck/blob/main/docs/BENCHMARK.md).

Closing the issue now, but please feel free to reopen if there's any follow-up questions!
