### ISSUE TITLE
Better organization of the datasets

### ISSUE THREAD

**Issue by jiadingfang** [KAIR-BAIR/dycheck#9]
Hi,

Thanks for the great effort, dynamic video data is becoming more and more an interesting topic, and analyzing dataset themselves is a critical part to the solution.

I appreciate that you provided data on google drive. But Google drive is notoriously hard to work with from command line (typical for remote machines), especially with separate folders like you provided. I wish that you could either provide a concentrated zip file or equivalent for the whole iPhone dataset, or maybe host it somewhere else like Huggingface.

Thank you in advance.

**Comment by jiadingfang** [comment]
Sorry, the authors actually kindly provide script for downloading data in `scripts`. Refer to `DATASETS.md`.

**Comment by Junyi42** [comment]
> Hi,
> 
> Thanks for the great effort, dynamic video data is becoming more and more an interesting topic, and analyzing dataset themselves is a critical part to the solution.
> 
> I appreciate that you provided data on google drive. But Google drive is notoriously hard to work with from command line (typical for remote machines), especially with separate folders like you provided. I wish that you could either provide a concentrated zip file or equivalent for the whole iPhone dataset, or maybe host it somewhere else like Huggingface.
> 
> Thank you in advance.

Hi, I met the exact same issue when trying to download the dataset on a remote server. However, the `rclone` method also doesn't work for me due to an error when setting up the account. Could you please kindly share a zip file version of the iPhone dataset? Many thanks!

**Comment by Junyi42** [comment]
> > Hi,
> > Thanks for the great effort, dynamic video data is becoming more and more an interesting topic, and analyzing dataset themselves is a critical part to the solution.
> > I appreciate that you provided data on google drive. But Google drive is notoriously hard to work with from command line (typical for remote machines), especially with separate folders like you provided. I wish that you could either provide a concentrated zip file or equivalent for the whole iPhone dataset, or maybe host it somewhere else like Huggingface.
> > Thank you in advance.
> 
> Hi, I met the exact same issue when trying to download the dataset on a remote server. However, the `rclone` method also doesn't work for me due to an error when setting up the account. Could you please kindly share a zip file version of the iPhone dataset? Many thanks!

Problem solved. I found that the latest version of `rclone` comes with a very detailed account setup guide that works well, while the earlier version I installed with `apt` does not have the setup guide.

**Comment by jiadingfang** [comment]
Glad you solved it @Junyi42 ! I believe I went with `rclone` provided docker image.
